-- Generated by scripts/hypr2lua.
-- Source: omarchy-pinup-theme/hyprland.conf

local activeBorderColor = "rgb(004584)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  decoration = {},
})
